name: Project A CI

on:
  push:
    paths:
      - "project-a/**"
      - ".github/workflows/project-a.yml"
      - "shared-lib/**"
  pull_request:
    paths:
      - "project-a/**"
      - "shared-lib/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install ./shared-lib
          pip install -r project-a/requirements.txt

      - name: Run tests
        run: |
            pip install -e ./shared-lib
            export PYTHONPATH=$PWD/shared-lib
            pytest project-a/tests